# Generated by Django 3.1.2 on 2020-10-22 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201022_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='age_limit',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
