# Generated by Django 3.1.2 on 2020-10-22 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20201022_1640'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='director',
            unique_together={('name', 'last_name')},
        ),
        migrations.AlterUniqueTogether(
            name='movie',
            unique_together={('title', 'released')},
        ),
        migrations.AddField(
            model_name='movie',
            name='country',
            field=models.ManyToManyField(to='core.Country'),
        ),
    ]
